title: SYPortfolio Showcase
author: Sorat Yamockul
email: syamockul@goprecise.com
description: > # this means to ignore newlines until "baseurl:"
 This new website is replacing the old syportfolio.net website, which is no longer active.  This is a new way to display and showcase my work as a web developer and ux/ui designer.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
