title: New and Improve SYportfolio
author: Sorat Yamockul
email: syamockul@goprecise.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  I am a UX/UI Developer that started my career as a graphic designer.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
